spring:
    profiles: dev
name: zhaowenlong
dns: 
        - 127.0.0.1
        - 127.0.0.2 
    
---
name: zhao
spring:
    profiles: pro
server:
    - www.baidu.com: 192.168.1.1
    - www.126.com: 192.168.1.2
