spring:
    profiles: dev
name: zhaowenlong
dns: 
    name: www.baiud.com
    ip: 127.0.0.1
---
name: zhao
spring:
    profiles: pro
server:
    - www.baidu.com: 192.168.1.1
    - www.126.com: 192.168.1.2
